FROM geerlingguy/php-apache:latest

RUN rm /var/www/html/index.html
COPY index.php /var/wwww/html/index.php

COPY ./ports.conf /etc/apache2/ports.conf
COPY .apache.conf /etc/apache/sites-enabled/000-default.conf